export const REHEARSAL_NETWORK_NODE_COUNT = 10
export const REHEARSAL_NETWORK_BOOTSTRAP_NODE_COUNT = 1
export const REHEARSAL_NETWORK_VALIDATOR_COUNT = Math.max(
  0,
  REHEARSAL_NETWORK_NODE_COUNT - REHEARSAL_NETWORK_BOOTSTRAP_NODE_COUNT
)
export const REHEARSAL_NETWORK_LEAD_SECONDS = 8 * 60
export const REHEARSAL_NETWORK_SEED_FLIP_COUNT = 30
export const REHEARSAL_DEFAULT_SOLVER_PARTICIPANT_COUNT = 1
export const REHEARSAL_SHARED_NODE_PARTICIPANT_START_DELAY_MS = 500

export function buildRehearsalNetworkPayload({connectApp = false} = {}) {
  return {
    nodeCount: REHEARSAL_NETWORK_NODE_COUNT,
    firstCeremonyLeadSeconds: REHEARSAL_NETWORK_LEAD_SECONDS,
    seedFlipCount: REHEARSAL_NETWORK_SEED_FLIP_COUNT,
    connectApp,
    connectCountdownSeconds: null,
  }
}
